CREATE SCHEMA IF NOT EXISTS inventory;
SET search_path TO inventory;

CREATE TABLE IF NOT EXISTS sku_mappings (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    sku_pos VARCHAR(8) NOT NULL,
    sku_erp VARCHAR(18) NOT NULL,
    handle VARCHAR(70) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tiendas_info (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    tienda_id VARCHAR(5) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    region VARCHAR(25) NOT NULL,
    timezone VARCHAR(70) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS catalogo_productos (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    sku_erp INT NOT NULL REFERENCES sku_mappings(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    nombre VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS catalogo_proveedores (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    sku_erp INT NOT NULL REFERENCES sku_mappings(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha_vigencia DATE NOT NULL,
    costo_mxn DECIMAL(10, 2) NOT NULL,
    proveedor VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS snapshots(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    fecha DATE NOT NULL,
    tienda_id INT NOT NULL REFERENCES tiendas_info(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    sku_erp INT NOT NULL REFERENCES sku_mappings(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    cantidad_en_stock INT NOT NULL
);